name: XML File

on:
  workflow_dispatch:  

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3   

    - name: Read XML File
      run: |         
          dir 
          
          if (Get-Content .\*.xml)  {
          Write-Output "    "
          Write-Output "******************************** XML File ********************************"
          Write-Output "    "
          type *.xml
          }
          else  {
          Write-Output "  "
          Write-Output "XML file is blank"
          }
